### ISSUE TITLE
Example HelloEDAM app fails at runtime on 4.1.2 / 22.0.4

### ISSUE THREAD

**Issue by thenoviceoof** [evernote/evernote-sdk-android#39]
After upgrading to ADT 22.0.1, I noticed that one of my apps started crashing when reaching code provided by the Evernote SDK. Trying to debug, I found that it was still crashing when using the example HelloEDAM project, crashing on startup (fairly certain I've successfully run the example on this computer/configuration before (minus version changes)). Logcat captured the following exception:

http://pastebin.com/raw.php?i=z7HDpN9D

Possibly relevant info:

 - ADT 22.0.1 / 22.0.4
 - Android 4.1.2 via Cyanogenmod, running on an original Galaxy S
 - Eclipse 3.7.2 / java-8-oracle / Ubuntu 12.04 (also tested it with java-7-oracle, java-1.7.0-openjdk-amd64)
 - Yes, I'm using the latest `master`
 - Created some new workspaces to make sure there weren't problems with that

**Comment by vRallev** [comment]
There is a new demo app.
