### ISSUE TITLE
Using the Evernote SDK with Android Studio

### ISSUE THREAD

**Issue by kennym** [evernote/evernote-sdk-android#40]
I am trying to set-up an Android Studio project with the Evernote SDK, but it does not seem to work.
 
What I have tried:
* Adding the JARs to the project module dependencies - this does not seem to work, because Android Studio uses Gradle. (http://stackoverflow...-android-studio)
* Adding the evernote-sdk-android/library to the project, as described in this answer on StackOverflow: http://stackoverflow...16639227/221612

This answer got me a little farther, but when compiling Evernote Android Studio is complaining:

Information:Compilation completed with 101 errors and 0 warnings in 16 sec
Information:101 errors
Information:0 warnings
Error:Gradle: Execution failed for task ':libraries:evernote-sdk:compileRelease'.
> Compilation failed; see the compiler error output for details.
/Users/kenny/AndroidStudioProjects/GreenDiaryProject/libraries/evernote-sdk/src/com/evernote/client/android/AsyncBusinessNoteStoreClient.java
    Error:Error:line (28)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (29)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (30)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (31)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (32)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (33)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (34)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (35)Gradle: package com.evernote.thrift does not exist
    Error:Error:line (36)Gradle: package com.evernote.thrift.protocol does not exist
    Error:Error:line (37)Gradle: package com.evernote.thrift.transport does not exist
    Error:Error:line (60)Gradle: cannot find symbol class TProtocol
    Error:Error:line (60)Gradle: cannot find symbol class TProtocol
    Error:Error:line (60)Gradle: cannot find symbol class TTransportException
    Error:Error:line (79)Gradle: cannot find symbol class Note
    Error:Error:line (79)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (79)Gradle: cannot find symbol class Note
    Error:Error:line (79)Gradle: cannot find symbol class EDAMUserException
    Error:Error:line (79)Gradle: cannot find symbol class EDAMSystemException
    Error:Error:line (79)Gradle: cannot find symbol class TException
    Error:Error:line (79)Gradle: cannot find symbol class EDAMNotFoundException
    Error:Error:line (100)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (100)Gradle: cannot find symbol class EDAMUserException
    Error:Error:line (100)Gradle: cannot find symbol class EDAMSystemException
    Error:Error:line (100)Gradle: cannot find symbol class TException
    Error:Error:line (100)Gradle: cannot find symbol class EDAMNotFoundException
    Error:Error:line (119)Gradle: cannot find symbol class Notebook
    Error:Error:line (119)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (119)Gradle: cannot find symbol class TException
    Error:Error:line (119)Gradle: cannot find symbol class EDAMUserException
    Error:Error:line (119)Gradle: cannot find symbol class EDAMSystemException
    Error:Error:line (119)Gradle: cannot find symbol class EDAMNotFoundException
    Error:Error:line (131)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (131)Gradle: cannot find symbol class TException
    Error:Error:line (131)Gradle: cannot find symbol class EDAMUserException
    Error:Error:line (131)Gradle: cannot find symbol class EDAMSystemException
    Error:Error:line (131)Gradle: cannot find symbol class EDAMNotFoundException
    Error:Error:line (149)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (149)Gradle: cannot find symbol class Notebook
    Error:Error:line (149)Gradle: cannot find symbol class TException
    Error:Error:line (149)Gradle: cannot find symbol class EDAMUserException
    Error:Error:line (149)Gradle: cannot find symbol class EDAMSystemException
    Error:Error:line (149)Gradle: cannot find symbol class EDAMNotFoundException
/Users/kenny/AndroidStudioProjects/GreenDiaryProject/libraries/evernote-sdk/src/com/evernote/client/android/AsyncLinkedNoteStoreClient.java
    Error:Error:line (28)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (29)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (30)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (31)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (32)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (33)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (34)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (35)Gradle: package com.evernote.thrift does not exist
    Error:Error:line (36)Gradle: package com.evernote.thrift.protocol does not exist
    Error:Error:line (37)Gradle: package com.evernote.thrift.transport does not exist
    Error:Error:line (63)Gradle: cannot find symbol class TProtocol
    Error:Error:line (63)Gradle: cannot find symbol class TProtocol
    Error:Error:line (63)Gradle: cannot find symbol class TTransportException
    Error:Error:line (101)Gradle: cannot find symbol class Note
    Error:Error:line (101)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (101)Gradle: cannot find symbol class Note
    Error:Error:line (120)Gradle: cannot find symbol class Note
    Error:Error:line (120)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (120)Gradle: cannot find symbol class Note
    Error:Error:line (120)Gradle: cannot find symbol class EDAMUserException
    Error:Error:line (120)Gradle: cannot find symbol class EDAMSystemException
    Error:Error:line (120)Gradle: cannot find symbol class TException
    Error:Error:line (120)Gradle: cannot find symbol class EDAMNotFoundException
    Error:Error:line (135)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (145)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (145)Gradle: cannot find symbol class EDAMUserException
    Error:Error:line (145)Gradle: cannot find symbol class EDAMSystemException
    Error:Error:line (145)Gradle: cannot find symbol class TException
    Error:Error:line (145)Gradle: cannot find symbol class EDAMNotFoundException
    Error:Error:line (156)Gradle: cannot find symbol class Notebook
    Error:Error:line (156)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (167)Gradle: cannot find symbol class Notebook
    Error:Error:line (167)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (167)Gradle: cannot find symbol class TException
    Error:Error:line (167)Gradle: cannot find symbol class EDAMUserException
    Error:Error:line (167)Gradle: cannot find symbol class EDAMSystemException
    Error:Error:line (167)Gradle: cannot find symbol class EDAMNotFoundException
    Error:Error:line (187)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (198)Gradle: cannot find symbol class LinkedNotebook
    Error:Error:line (198)Gradle: cannot find symbol class TException
    Error:Error:line (198)Gradle: cannot find symbol class EDAMUserException
    Error:Error:line (198)Gradle: cannot find symbol class EDAMSystemException
/Users/kenny/AndroidStudioProjects/GreenDiaryProject/libraries/evernote-sdk/src/com/evernote/client/android/ClientFactory.java
    Error:Error:line (29)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (30)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (31)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (32)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (33)Gradle: package com.evernote.edam.userstore does not exist
    Error:Error:line (34)Gradle: package com.evernote.thrift does not exist
    Error:Error:line (35)Gradle: package com.evernote.thrift.protocol does not exist
    Error:Error:line (36)Gradle: package com.evernote.thrift.transport does not exist
/Users/kenny/AndroidStudioProjects/GreenDiaryProject/libraries/evernote-sdk/src/com/evernote/client/android/AsyncNoteStoreClient.java
    Error:Error:line (28)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (29)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (30)Gradle: package com.evernote.edam.error does not exist
    Error:Error:line (31)Gradle: package com.evernote.edam.notestore does not exist
    Error:Error:line (32)Gradle: package com.evernote.edam.type does not exist
    Error:Error:line (33)Gradle: package com.evernote.edam.userstore does not exist
    Error:Error:line (34)Gradle: package com.evernote.thrift does not exist
    Error:Error:line (35)Gradle: package com.evernote.thrift.protocol does not exist

Can you reproduce this issue?

**Comment by hannesstruss** [comment]
For everyone stumbling upon this, there seems to be an in-development branch including Gradle/aar build that you can check out and install to your local Maven repo: https://github.com/evernote/evernote-sdk-android/tree/android_studio

**Comment by camdenfullmer** [comment]
@tyvsmith Is there any update on adding an .aar to Maven Central? The Android Studio integration with gradle still does not work because the library is still packaged as an .apklib.

**Comment by vRallev** [comment]
@camdenfullmer No, there is no official build, yet. But I've published a snapshot build to maven central. Take a look at this branch: https://github.com/evernote/evernote-sdk-android/tree/android_studio

Note that this is work in progress, so assume that there are issues.

**Comment by camdenfullmer** [comment]
@vRallev thanks, I have it working now!

**Comment by vRallev** [comment]
We released version 2.0.0-RC1 on master. Android Studio is now supported.
