### ISSUE TITLE
Way to dismiss EvernoteOAuthActivity on back button press

### ISSUE THREAD

**Issue by jainsanyam** [evernote/evernote-sdk-android#43]
When I call EvernoteSession.authenticate(), that triggers EvernoteOAuthActivity to authorize the client.
It loads the webview for Evernote OAuth authorization, progress dialog is shown.
There is no way by which user can stop authenticating or go back until the web page is loaded.

Is there a way to finish this activity or handle back button on the progress dialog?

**Comment by vRallev** [comment]
The main Evernote app now authenticates the user. There is also a cancel button in the dialog. Please update to the new SDK version 2.0.0.
