### ISSUE TITLE
[Bug] EvernoteOAuthActivity not translated

### ISSUE THREAD

**Issue by markiyan-antonyuk** [evernote/evernote-sdk-android#48]
Steps to reproduce:
1) Open EvernoteOAuthActivity with english language on device
2) Head back to previous activity
3) Change language in device settings
4) Open app and reopen EvernoteOAuthActivity
Result: EvernoteOAthActivity is left translated in previous language

**Comment by vRallev** [comment]
That is fixed. The new version 2.0.0 uses the main Evernote app for authentication and the fallback EvernoteOAuthActivity now listens for config changes.
